### ISSUE TITLE
Contribution rules change proposal

### ISSUE THREAD

**Issue by timidri** [puppetlabs-seteam/control-repo#109]
To streamline control repo development and support CD4PE workflows I propose the following changes to contribution rules:
- master becomes the default branch and target for pull requests
- feature branches are removed from this repo and created in forks
- creation of new branches in this repo is restricted

A question remains how to automate updates to the production branch after a master change to support CD4PE-less workflows.

**Comment by stephenkpotter** [comment]
@timidri the goal is that all checkins to master will flow thru CD4PE as part of this part of the overall vision. I am seeking internal community support at this time. The primary goal is of course for demo environment to work. I feel like this could be a good discussion in the weekly SE meeting to communicate first so that any content folks don't want to lose gets into the production branch.
 https://docs.google.com/document/d/1tzUeteb7p7NyTJN9X8prvfWbB3ZKTMls_Xje4iyz_2g/edit

**Comment by reidmv** [comment]
I'm strongly in support of the first bullet point, "master becomes the default branch and target for pull requests". I think we can do that immediately if we don't (yet) delete the "production" branch. We can iterate on the process afterwards to figure out how to remove/maintain production.

**Comment by cdrobey** [comment]
@timidri and @stephenkpotter I'm assuming the repo is duplexed to a gitlab environment that's built by hydra.  That allows the se-repo to become the source of truth?

**Comment by timidri** [comment]
@cdrobey Indeed, this repo is the source of truth and every hydra-based demo environment will contain a snapshot of the control repo taken at the time of environment creation.

**Comment by stephenkpotter** [comment]
@reidmv Are you able to make the change to the master branch while @timidri is at Kubecon?

**Comment by reidmv** [comment]
@stephenkpotter I've created a master branch and made it the default.

I have not cleaned up existing feature branches, nor put in place restrictions on creating them.

**Comment by psreed** [comment]
Closing for now since this is years old and likely no longer applies.
